# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      MYSQL_DATABASE: collex_development
      MYSQL_ROOT_PASSWORD: super-secret
      MYSQL_USER: collex
      MYSQL_PASS: super-secret

  web: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    depends_on:
      - db
    links:
      - db:db

# volumes: 
#  - ./mysql-data:/var/lib/mysql
